name: myprofile
description: flutter application1
publish_to: 'none' 
version: 1.0.0+1     
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  google_fonts: ^2.1.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets: 
    - assets/th.jpg
    
